**Q1: What is a Python library? Why do we use Python libraries?**

A Python library is a collection of pre-written code that provides useful functions and tools for performing specific tasks. Libraries simplify development by allowing programmers to reuse code rather than writing it from scratch.

Libraries provide optimized code that can perform complex tasks with just a few lines, making the code easier to write and maintain.

Instead of writing functions from scratch, you can reuse the code that others have already written and tested.

Libraries are written by experts and the Python community, ensuring reliable, efficient, and often widely-used solutions.

**Q2: What is the difference between Numpy array and List?**

1) Numpy array are homogeneous.
1) Python lists are heterogeneous.

2) Numpy array are faster for numerical computations due to optimized C/C++ implementation.
2) Python lists are slower because it’s a general-purpose container.

3) More memory-efficient because of the fixed data types.
3) Consumes more memory due to its flexibility in storing different data types.

4) Supports element-wise operations (like addition, multiplication).
4) Does not support element-wise operations directly. Requires loops or list comprehensions.

5) Size is fixed after creation (but can be modified using functions like np.resize).
5) Can grow or shrink dynamically (can append, remove elements).

6) Automatically converts data types (e.g., integers to floats) for efficiency.
6) No automatic conversion; keeps mixed data types as they are.

**Q3: Find the shape, size and dimension of the following array?  
[[1, 2, 3, 4]  
[5, 6, 7, 8],  
[9, 10, 11, 12]]**

In [22]:
import numpy as np

In [9]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [10]:
arr.shape

(3, 4)

In [11]:
arr.size

12

In [12]:
arr.ndim

2

**Q4: Write python code to access the first row of the following array?  
[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12]]**

In [13]:
arr2=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

In [14]:
arr2[0]

array([1, 2, 3, 4])

**Q5: How do you access the element at the third row and fourth column from the given numpy array?  
[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12]]**

In [15]:
arr3= np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [17]:
arr3[2][3]

np.int64(12)

In [19]:
arr3[2,3]

np.int64(12)

**Q6: Write code to extract all odd-indexed elements from the given numpy array?  
[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12]]**

In [20]:
arr4= np.array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]])

In [21]:
odd_elements= arr4[1::2, 1::2]
print(odd_elements)

[[6 8]]


**Q7: How can you generate a random 3x3 matrix with values between 0 and 1?**

In [24]:
arr5=np.random.rand(3,3)
print(arr5)

[[0.24153034 0.25141832 0.56417429]
 [0.21469035 0.94673029 0.74918561]
 [0.45269958 0.22598333 0.14201082]]


**Q8: Describe the difference between np.random.rand and np.random.randn?**

**np.random.rand()**: Generates random numbers from a uniform distribution between 0 and 1.  
Range: All values are between 0 and 1.  
**np.random.randn()**: Generates random numbers from a standard normal distribution (also called a Gaussian distribution) with:  
Mean = 0  
Standard deviation = 1    
Range: Values can be positive or negative and are typically centered around 0 (with a majority falling within the range of [-3, 3]).

**Q9: Write code to increase the dimension of the following array?  
[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12]]**

In [27]:
arr6=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr7=np.expand_dims(arr6, axis=0)
print(arr7)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


**Q10: How to transpose the following array in NumPy?  
[[1, 2, 3, 4],  
[5, 6, 7, 8],  
[9, 10, 11, 12]]**

In [28]:
arr8=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

In [29]:
arr8.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

**Q11: Consider the following matrix:  
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]  
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]  
Perform the following operation using Python:  
1)Index wise multiplication   
2)Matrix multiplication   
3)Add both the matrics    
4)Subtract matrix B from A    
5)Divide Matrix B by A**

In [36]:
A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [37]:
index_wise_mul=A*B
print(index_wise_mul)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [39]:
matrix_mul= A@B.T
print(matrix_mul)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [40]:
add=A+B
print(add)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [41]:
sub=A-B
print(sub)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
div=B/A
print(div)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Q12: Which function in Numpy can be used to swap the byte order of an array?**

you can use the **byteswap()** function to swap the byte order of an array.

**Q13: What is the significance of the np.linalg.inv function?**

The np.linalg.inv function in NumPy is used to compute the inverse of a given square matrix. In linear algebra, the inverse of a matrix A is a matrix 
𝐴^-1 such that:  
**A.A^-1= I**

In [46]:
C=np.array([[1, 2], [3, 4]])
C_inv=np.linalg.inv(C)
print(C_inv)
identity=np.dot(C, C_inv)
print(identity)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


**Q14: What does the np.reshape function do, and how is it used?**

The np.reshape function in NumPy is used to change the shape or dimensions of an existing array without changing its data. It rearranges the elements of the array into a new shape that you specify, as long as the total number of elements remains the same.

In [47]:
arr9 = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into a 2x3 matrix
reshaped_arr = np.reshape(arr9, (2, 3))

print("Original Array:")
print(arr9)

print("Reshaped Array (2x3):")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6]
Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


**Q15: What is broadcasting in Numpy?**

Broadcasting in NumPy refers to the ability of NumPy to perform element-wise operations on arrays with different shapes, making it easier to perform operations without explicitly replicating data. Broadcasting automatically expands the dimensions of smaller arrays so that they match the shape of larger arrays during operations like addition, multiplication, etc.