In [1]:
import numpy as np

In [2]:
#numpy- array manipulation

In [4]:
arr=np.random.randint(1,10, (4,4))

In [5]:
arr

array([[4, 7, 2, 9],
       [9, 9, 5, 2],
       [3, 4, 3, 7],
       [9, 3, 1, 2]], dtype=int32)

In [6]:
arr.reshape(8,2)

array([[4, 7],
       [2, 9],
       [9, 9],
       [5, 2],
       [3, 4],
       [3, 7],
       [9, 3],
       [1, 2]], dtype=int32)

In [8]:
arr.T

array([[4, 9, 3, 9],
       [7, 9, 4, 3],
       [2, 5, 3, 1],
       [9, 2, 7, 2]], dtype=int32)

In [9]:
arr.flatten()

array([4, 7, 2, 9, 9, 9, 5, 2, 3, 4, 3, 7, 9, 3, 1, 2], dtype=int32)

In [11]:
np.expand_dims(arr, axis=1) #(4,1,4)

array([[[4, 7, 2, 9]],

       [[9, 9, 5, 2]],

       [[3, 4, 3, 7]],

       [[9, 3, 1, 2]]], dtype=int32)

In [13]:
np.expand_dims(arr, axis=0) #(1,4,4)

array([[[4, 7, 2, 9],
        [9, 9, 5, 2],
        [3, 4, 3, 7],
        [9, 3, 1, 2]]], dtype=int32)

In [14]:
data=np.array([[1],[2],[3]])

In [15]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
np.repeat(data, 2)

array([1, 1, 2, 2, 3, 3])

In [17]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [18]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [19]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
#numpy- binary operators

In [22]:
arr1=np.random.randint(1,10, (3,4))
arr2=np.random.randint(1,10, (3,4))

In [23]:
arr1

array([[4, 9, 7, 4],
       [7, 6, 9, 4],
       [4, 9, 6, 1]], dtype=int32)

In [24]:
arr2

array([[1, 5, 7, 7],
       [5, 4, 5, 3],
       [1, 6, 1, 2]], dtype=int32)

In [25]:
arr1+arr2

array([[ 5, 14, 14, 11],
       [12, 10, 14,  7],
       [ 5, 15,  7,  3]], dtype=int32)

In [26]:
arr1*arr2

array([[ 4, 45, 49, 28],
       [35, 24, 45, 12],
       [ 4, 54,  6,  2]], dtype=int32)

In [27]:
arr1/arr2

array([[4.        , 1.8       , 1.        , 0.57142857],
       [1.4       , 1.5       , 1.8       , 1.33333333],
       [4.        , 1.5       , 6.        , 0.5       ]])

In [28]:
arr1-arr2

array([[ 3,  4,  0, -3],
       [ 2,  2,  4,  1],
       [ 3,  3,  5, -1]], dtype=int32)

In [29]:
arr1**arr2

array([[     4,  59049, 823543,  16384],
       [ 16807,   1296,  59049,     64],
       [     4, 531441,      6,      1]], dtype=int32)

In [30]:
arr1>arr2

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [31]:
#numpy- string functions

In [32]:
arr3= np.array(["deep", "singh"])

In [33]:
arr3

array(['deep', 'singh'], dtype='<U5')

In [34]:
np.char.upper(arr3)

array(['DEEP', 'SINGH'], dtype='<U5')

In [35]:
np.char.capitalize(arr3) #first letter

array(['Deep', 'Singh'], dtype='<U5')

In [37]:
np.char.title(arr3) #first letter of every word

array(['Deep', 'Singh'], dtype='<U5')

In [38]:
#numpy- mathematical functions

In [39]:
arr1

array([[4, 9, 7, 4],
       [7, 6, 9, 4],
       [4, 9, 6, 1]], dtype=int32)

In [40]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849,  0.6569866 , -0.7568025 ],
       [ 0.6569866 , -0.2794155 ,  0.41211849, -0.7568025 ],
       [-0.7568025 ,  0.41211849, -0.2794155 ,  0.84147098]])

In [41]:
np.cos(arr1)

array([[-0.65364362, -0.91113026,  0.75390225, -0.65364362],
       [ 0.75390225,  0.96017029, -0.91113026, -0.65364362],
       [-0.65364362, -0.91113026,  0.96017029,  0.54030231]])

In [42]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566,  0.87144798,  1.15782128],
       [ 0.87144798, -0.29100619, -0.45231566,  1.15782128],
       [ 1.15782128, -0.45231566, -0.29100619,  1.55740772]])

In [43]:
np.log10(arr1)

array([[0.60205999, 0.95424251, 0.84509804, 0.60205999],
       [0.84509804, 0.77815125, 0.95424251, 0.60205999],
       [0.60205999, 0.95424251, 0.77815125, 0.        ]])

In [44]:
np.exp(arr1)

array([[5.45981500e+01, 8.10308393e+03, 1.09663316e+03, 5.45981500e+01],
       [1.09663316e+03, 4.03428793e+02, 8.10308393e+03, 5.45981500e+01],
       [5.45981500e+01, 8.10308393e+03, 4.03428793e+02, 2.71828183e+00]])

In [45]:
np.power(arr1, 2)

array([[16, 81, 49, 16],
       [49, 36, 81, 16],
       [16, 81, 36,  1]], dtype=int32)

In [46]:
np.mean(arr1)

np.float64(5.833333333333333)

In [47]:
np.median(arr1)

np.float64(6.0)

In [48]:
np.std(arr1)

np.float64(2.4094720491334933)

In [49]:
np.var(arr1)

np.float64(5.8055555555555545)

In [50]:
np.min(arr1)

np.int32(1)

In [51]:
np.max(arr1)

np.int32(9)

In [52]:
#numpy- arithmetic operations

In [53]:
arr1

array([[4, 9, 7, 4],
       [7, 6, 9, 4],
       [4, 9, 6, 1]], dtype=int32)

In [54]:
arr2

array([[1, 5, 7, 7],
       [5, 4, 5, 3],
       [1, 6, 1, 2]], dtype=int32)

In [55]:
arr1-arr2

array([[ 3,  4,  0, -3],
       [ 2,  2,  4,  1],
       [ 3,  3,  5, -1]], dtype=int32)

In [56]:
np.subtract(arr1, arr2)

array([[ 3,  4,  0, -3],
       [ 2,  2,  4,  1],
       [ 3,  3,  5, -1]], dtype=int32)

In [57]:
np.multiply(arr1, arr2)

array([[ 4, 45, 49, 28],
       [35, 24, 45, 12],
       [ 4, 54,  6,  2]], dtype=int32)

In [58]:
np.mod(arr1, arr2)

array([[0, 4, 0, 4],
       [2, 2, 4, 1],
       [0, 3, 0, 1]], dtype=int32)

In [59]:
np.power(arr1, arr2)

array([[     4,  59049, 823543,  16384],
       [ 16807,   1296,  59049,     64],
       [     4, 531441,      6,      1]], dtype=int32)

In [60]:
np.sqrt(arr1)

array([[2.        , 3.        , 2.64575131, 2.        ],
       [2.64575131, 2.44948974, 3.        , 2.        ],
       [2.        , 3.        , 2.44948974, 1.        ]])

In [61]:
#numpy- statistical functions

In [62]:
arr1

array([[4, 9, 7, 4],
       [7, 6, 9, 4],
       [4, 9, 6, 1]], dtype=int32)

In [63]:
np.mean(arr1)

np.float64(5.833333333333333)

In [65]:
np.std(arr1)

np.float64(2.4094720491334933)

In [66]:
np.median(arr1)

np.float64(6.0)

In [67]:
#sort, search and counting functions

In [69]:
arr4=np.array([2,5,1,7,9,23,4,0])

In [70]:
arr4

array([ 2,  5,  1,  7,  9, 23,  4,  0])

In [72]:
np.sort(arr4)

array([ 0,  1,  2,  4,  5,  7,  9, 23])

In [73]:
np.searchsorted(arr4,6)

np.int64(5)

In [75]:
arr5=np.array([1,2,7,0,0,45,0,3,0,56,0,0])

In [76]:
np.count_nonzero(arr5)

6

In [77]:
np.where(arr5>0)

(array([0, 1, 2, 5, 7, 9]),)

In [79]:
np.extract(arr5>2, arr5)

array([ 7, 45,  3, 56])

In [80]:
#numpy- byte swapping

In [81]:
arr5

array([ 1,  2,  7,  0,  0, 45,  0,  3,  0, 56,  0,  0])

In [82]:
arr5.byteswap()

array([  72057594037927936,  144115188075855872,  504403158265495552,
                         0,                   0, 3242591731706757120,
                         0,  216172782113783808,                   0,
       4035225266123964416,                   0,                   0])

In [83]:
arr5

array([ 1,  2,  7,  0,  0, 45,  0,  3,  0, 56,  0,  0])

In [84]:
arr5.byteswap(True)

array([  72057594037927936,  144115188075855872,  504403158265495552,
                         0,                   0, 3242591731706757120,
                         0,  216172782113783808,                   0,
       4035225266123964416,                   0,                   0])

In [85]:
arr5

array([  72057594037927936,  144115188075855872,  504403158265495552,
                         0,                   0, 3242591731706757120,
                         0,  216172782113783808,                   0,
       4035225266123964416,                   0,                   0])

In [86]:
#numpy- copy and views

In [89]:
arr4

array([ 0,  1,  2,  4,  5,  7,  9, 23])

In [90]:
a=np.copy(arr4)

In [91]:
b=arr4.view()

In [92]:
b

array([ 0,  1,  2,  4,  5,  7,  9, 23])

In [93]:
b[0]=234

In [94]:
arr4

array([234,   1,   2,   4,   5,   7,   9,  23])

In [95]:
#numpy- matrix library

In [96]:
import numpy.matlib as nm

In [97]:
#This module provides functions for creating matrices, which are specific 2D arrays often used in linear algebra operations.

In [98]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [99]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [101]:
#numpy- linear algebra

In [104]:
arr6=np.random.randint([[2,3], [4,5]])

In [105]:
arr7=np.random.randint([[5,3], [2,5]])

In [106]:
arr6

array([[1, 2],
       [1, 3]], dtype=int32)

In [107]:
arr7

array([[1, 0],
       [1, 0]], dtype=int32)

In [109]:
np.dot(arr6, arr7)

array([[3, 0],
       [4, 0]], dtype=int32)

In [110]:
arr6@arr7

array([[3, 0],
       [4, 0]], dtype=int32)

In [111]:
import random

In [112]:
random.choice((1,2,3,4,5,6))

5

In [113]:
random.choice('Deepika')

'p'

In [114]:
random.randrange(1,10)

3

In [120]:
random.random() #The function random.random() generates a random floating-point number between 0.0 and 1.0, including 0.0 but excluding 1.0.

0.34530857778170077

In [116]:
lis=[1,2,3,4,5]
random.shuffle(lis)

In [117]:
lis

[2, 5, 4, 3, 1]

In [119]:
random.uniform(7,14)  #The function random.uniform(7, 14) generates a random floating-point number between 7 and 14 (both inclusive).

7.632984838772777