In [2]:
#NumPy- Numerical Python
#it is used for working with arrays and performing mathematical operations on large, multi- dimensional data

In [3]:
import numpy as np

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
print(np.__version__)

2.1.1


In [6]:
l=[1,2,3,4,5]

In [7]:
np.array(l)

array([1, 2, 3, 4, 5])

In [8]:
arr=np.array(l)

In [9]:
type(arr)

numpy.ndarray

In [10]:
#nd means n dimensional

In [11]:
np.asarray(l)

array([1, 2, 3, 4, 5])

**np.asarray()**: It will not create a new array if the input is already an array or array-like object. It reuses the existing memory  
**np.array()**: Always returns a new copy, even if the input is already an array.

In [12]:
np.array([[1,2,3], [2,3,4]]) #two dimensional array

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
arr1=np.array([[1,2,3], [2,3,4]])

In [14]:
arr.ndim

1

In [15]:
arr1.ndim

2

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

**used to create matrix from any input.  Unlike a regular NumPy array, which can have multiple dimensions, a matrix is always 2-dimensional and follows the rules of matrix algebra.**

In [19]:
mat= np.matrix(l)

In [20]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

**np.asarray()**: Converts the input to a base ndarray object, regardless of the input type.  
**np.asanyarray()**: Converts the input only if it’s not already a subclass of ndarray. If it is a subclass, it keeps the subclass.

In [21]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
a=arr #shallow copy

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[0]=100

In [27]:
arr

array([100,   2,   3,   4,   5])

In [28]:
a

array([100,   2,   3,   4,   5])

In [29]:
b=np.copy(arr) #deep copy

In [30]:
b

array([100,   2,   3,   4,   5])

In [31]:
b[0]=234

In [32]:
b

array([234,   2,   3,   4,   5])

In [33]:
arr

array([100,   2,   3,   4,   5])

In [34]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

**np.fromfunction()** generates an array of indices by executing a function corresponding to the shape of the output array.

In [36]:
(i*i for i in range(5))

<generator object <genexpr> at 0x0000022D48F5E330>

In [37]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [38]:
iterable=(i*i for i in range(5))

In [39]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

The **np.fromiter()** function in NumPy is used to create a 1-dimensional array from an iterable (such as a list, tuple, generator, or any other object that supports iteration). It reads elements from the iterable and constructs an array with those values.

In [40]:
np.fromstring("23 34 56", sep= " ")

array([23., 34., 56.])

**np.fromstring()** in NumPy is a function used to create a 1-dimensional array from a string of text or binary data. It interprets the string as a sequence of values and converts it into a NumPy array.

In [41]:
np.fromstring("23,34,56", sep= ",")

array([23., 34., 56.])

In [42]:
arr

array([100,   2,   3,   4,   5])

In [43]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [47]:
arr.size #no. of elements

5

In [45]:
arr1.size

6

In [46]:
arr.shape 

(5,)

In [48]:
arr1.shape

(2, 3)

In [49]:
arr.dtype

dtype('int64')

In [50]:
arr1.dtype

dtype('int64')

In [51]:
range(5)

range(0, 5)

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [53]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [56]:
np.arange(0.4,10.2)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [58]:
np.arange(0.4,10.4, 0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [59]:
list(np.arange(0.4,10.4, 0.2))

[np.float64(0.4),
 np.float64(0.6000000000000001),
 np.float64(0.8000000000000002),
 np.float64(1.0000000000000002),
 np.float64(1.2000000000000002),
 np.float64(1.4000000000000004),
 np.float64(1.6000000000000005),
 np.float64(1.8000000000000003),
 np.float64(2.0000000000000004),
 np.float64(2.2000000000000006),
 np.float64(2.400000000000001),
 np.float64(2.6000000000000005),
 np.float64(2.8000000000000007),
 np.float64(3.000000000000001),
 np.float64(3.2000000000000006),
 np.float64(3.400000000000001),
 np.float64(3.600000000000001),
 np.float64(3.800000000000001),
 np.float64(4.000000000000002),
 np.float64(4.200000000000001),
 np.float64(4.400000000000002),
 np.float64(4.600000000000001),
 np.float64(4.800000000000002),
 np.float64(5.000000000000002),
 np.float64(5.200000000000002),
 np.float64(5.400000000000002),
 np.float64(5.600000000000002),
 np.float64(5.8000000000000025),
 np.float64(6.000000000000002),
 np.float64(6.200000000000002),
 np.float64(6.400000000000002),
 np.float

In [61]:
np.linspace(1, 5, 20)  #used to generate evenly spaced numbers over a specified interval. 

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [63]:
np.logspace(1,5, 10)  #generates numbers spaced evenly on a logarithmic scale.

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [64]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [69]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [71]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
arr2= np.ones((3,4))

In [74]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
arr2+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [76]:
arr2*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [77]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [78]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
arr3=np.eye(5)

In [80]:
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
import pandas as pd

In [82]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.5 MB 3.6 MB/s eta 0:00:04
   - -------------------------------------- 0.5/11.5 MB 5.0 MB/s eta 0:00:03
   --- ------------------------------------ 1.1/11.5 MB 8.7 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.5 MB 12.5 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/11.5 MB 12.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.5 MB 16.5 MB/s eta 0:00:01
   -------------------- ------------------- 6.0/11.5 MB 19.2 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.5 MB 21.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 20.8 MB/s eta 0:00:01
   -------------------------------- ------- 9.3/11.5 MB 20.6 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 20.4 MB/s eta 0:00:01
   -------------------------------------- - 11.1/11.5 MB 23.4 MB/s eta 0:0


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [84]:
pd.DataFrame(arr3)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [86]:
np.random.rand(2,3) #generates a 2x3 NumPy array with random floating-point numbers uniformly distributed between 0 and 1.

array([[0.00103801, 0.74441053, 0.15390982],
       [0.93263279, 0.83508362, 0.68664915]])

In [88]:
np.random.randn(2,3) #generates a 2x3 NumPy array with random numbers drawn from the standard normal distribution (also called the Gaussian distribution), which has a mean of 0 and a standard deviation of 1.

array([[ 0.87620613, -1.74800117,  0.74953194],
       [-0.08427491,  1.57622237, -0.07502553]])

In [89]:
np.random.randint(1,5, (3,4))

array([[2, 1, 1, 4],
       [4, 3, 1, 4],
       [3, 4, 3, 3]], dtype=int32)

In [90]:
arr4= np.random.randint(1,5, (3,4))

In [91]:
arr4

array([[2, 3, 2, 4],
       [3, 3, 3, 4],
       [2, 1, 3, 3]], dtype=int32)

In [92]:
arr4.size

12

In [93]:
arr4.shape

(3, 4)

In [94]:
arr4.reshape(6,2)

array([[2, 3],
       [2, 4],
       [3, 3],
       [3, 4],
       [2, 1],
       [3, 3]], dtype=int32)

In [95]:
arr4.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [96]:
arr4.reshape(2,6)

array([[2, 3, 2, 4, 3, 3],
       [3, 4, 2, 1, 3, 3]], dtype=int32)

In [97]:
arr4.reshape(4,3)

array([[2, 3, 2],
       [4, 3, 3],
       [3, 4, 2],
       [1, 3, 3]], dtype=int32)

In [98]:
arr4.reshape(4,-1)

array([[2, 3, 2],
       [4, 3, 3],
       [3, 4, 2],
       [1, 3, 3]], dtype=int32)

In [99]:
arr4.reshape(4,-156568)

array([[2, 3, 2],
       [4, 3, 3],
       [3, 4, 2],
       [1, 3, 3]], dtype=int32)

In [100]:
arr4.reshape(2,2,3)

array([[[2, 3, 2],
        [4, 3, 3]],

       [[3, 4, 2],
        [1, 3, 3]]], dtype=int32)

In [101]:
arr5=np.random.randint(1,10, (5,6))

In [102]:
arr5

array([[4, 8, 9, 7, 6, 5],
       [7, 4, 8, 6, 1, 3],
       [8, 8, 5, 9, 2, 4],
       [4, 2, 8, 5, 6, 9],
       [5, 2, 3, 5, 9, 4]], dtype=int32)

In [103]:
arr5>8

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False,  True, False]])

In [104]:
arr5[arr5>8]

array([9, 9, 9, 9], dtype=int32)

In [105]:
arr5[0]

array([4, 8, 9, 7, 6, 5], dtype=int32)

In [106]:
arr5[0, [0,1]]

array([4, 8], dtype=int32)

In [107]:
arr5[2:4, [2,3]]

array([[5, 9],
       [8, 5]], dtype=int32)

In [111]:
arr6= np.random.randint(1,3, (3,3))
arr7= np.random.randint(1,3, (3,3))

In [112]:
arr6

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 2]], dtype=int32)

In [113]:
arr7

array([[1, 1, 1],
       [1, 1, 1],
       [2, 1, 1]], dtype=int32)

In [114]:
arr6+arr7

array([[2, 2, 2],
       [3, 2, 2],
       [3, 3, 3]], dtype=int32)

In [115]:
arr6-arr7

array([[ 0,  0,  0],
       [ 1,  0,  0],
       [-1,  1,  1]], dtype=int32)

In [116]:
arr6*arr7 #index wise multiplication

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]], dtype=int32)

In [118]:
arr6@arr7 #matrix multiplication

array([[4, 3, 3],
       [5, 4, 4],
       [7, 5, 5]], dtype=int32)

In [119]:
arr6/arr7

array([[1. , 1. , 1. ],
       [2. , 1. , 1. ],
       [0.5, 2. , 2. ]])

In [120]:
arr6/0

C:\Users\Deepika\AppData\Local\Temp\ipykernel_23692\1351048935.py:1: RuntimeWarning: divide by zero encountered in divide
  arr6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [121]:
#numpy- broadcasting

NumPy broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes in a way that makes them compatible for element-wise operations. Instead of requiring arrays to have the exact same shape, NumPy "stretches" or "broadcasts" smaller arrays along dimensions so that they match the shape of the larger array.

In [122]:
arr6=np.zeros((3,4))

In [123]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
arr6+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [125]:
c=np.array([1,2,3,4])

In [126]:
arr6+c

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [127]:
d=np.array([3,4,5])

In [128]:
arr6+d

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [129]:
d=np.array([[3,4,5]])

In [138]:
arr7=arr6+d.T

In [139]:
d.T

array([[3],
       [4],
       [5]])

In [140]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [141]:
np.sqrt(arr7)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [142]:
np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [143]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [144]:
np.min(arr7)

np.float64(3.0)

In [145]:
np.max(arr7)

np.float64(5.0)